const ErrorCodes = {
  // Generic Errors
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",

  // Auth Errors
  USER_NOT_FOUND: "USER_NOT_FOUND",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  TOKEN_REUSE_DETECTED: "TOKEN_REUSE_DETECTED",

  // Conversation Errors
  CONVERSATION_NOT_FOUND: "CONVERSATION_NOT_FOUND",
  CONVERSATION_ALREADY_EXISTS: "CONVERSATION_ALREADY_EXISTS",
  INVALID_PARTICIPANTS: "INVALID_PARTICIPANTS",
  NOT_CONVERSATION_PARTICIPANT: "NOT_CONVERSATION_PARTICIPANT",
} as const;

export default ErrorCodes;