const ErrorCodes = {
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  USER_NOT_FOUND: "USER_NOT_FOUND",

  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",

  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

  VALIDATION_ERROR: "VALIDATION_ERROR",

  UNAUTHORIZED: "UNAUTHORIZED",
};

export default ErrorCodes;