const ErrorCodes = {
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  USER_NOT_FOUND: "USER_NOT_FOUND",

  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",

  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

  VALIDATION_ERROR: "VALIDATION_ERROR",

  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  TOKEN_REUSE_DETECTED : "TOKEN_REUSE_DETECTED",
};

export default ErrorCodes;