export enum SecurityEvent {
  REGISTER = "REGISTER",

  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILED = "LOGIN_FAILED",

  TOKEN_REFRESH = "TOKEN_REFRESH",
  TOKEN_REUSE = "TOKEN_REUSE",

  LOGOUT = "LOGOUT",
  LOGOUT_ALL = "LOGOUT_ALL",

  PASSWORD_CHANGED = "PASSWORD_CHANGED",

  DELETE_ACCOUNT = "DELETE_ACCOUNT",
}